spring:
  application:
    name: Rating-Service

  profiles:
    active: dev

  config:
    import: configserver:http://localhost:8085

  datasource:
    url: jdbc:mysql://localhost:3306/microservice_ratingservice
    username: root
    password: Deepak@29

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

server:
  port: 8083