spring:
  application:
    name: USER-SERVICE

  profiles:
    active: dev

  config:
    import: configserver:http://localhost:8085

  datasource:
    url: jdbc:mysql://localhost:3306/microservice_userservice
    username: root
    password: Deepak@29

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka


management:
  health:
    circuitbreakers:
      enabled: true

  endpoints:
    web:
      exposure:
        include: health,circuitbreakers

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true



resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state:
          seconds: 6
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: count_based
  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration:
          seconds: 3




